name: phr_app
description: "A Personal Health Record Flutter app with FHIR integration."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.2
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  uuid: ^4.2.1
  intl: ^0.20.2
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  workmanager: ^0.9.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.7
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  connectivity_plus: ^6.1.0
  flutter_gen: ^5.12.0
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
